# Generated by Django 5.1.1 on 2024-09-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charts_api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Candlestick",
        ),
        migrations.DeleteModel(
            name="LineChart",
        ),
    ]
